repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        files: ^server/(src|config)/
    -   id: end-of-file-fixer
        files: ^server/(src|config)/
    -   id: check-yaml
        files: ^server/(src|config)/
    -   id: check-added-large-files
        files: ^server/(src|config)/
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        files: ^server/(src|config)/
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.13
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format
