version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: 4atik
    restart: always
    ports:
      - '6969:6969'
    env_file:
      - ./server/.env
    volumes:
      - ./server/src:/usr/src/app/src
    networks:
      - chatik-network

  database:
    image: postgres:16
    container_name: database
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - chatik-network

volumes:
  pg_data:

networks:
  chatik-network:
