version: '3.9'

services:
  database:
    image: postgres:16
    container_name: database
    restart: always
    ports:
      - '6968:5432'
    env_file:
      - ./server/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - chatik-network

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "17027:27017"
    env_file:
      - ./server/.env
    volumes:
      - mongodb_data:/data/db
    networks:
      - chatik-network

  redis:
    image: redis:7
    container_name: redis
    restart: always
    env_file:
      - ./server/.env
    volumes:
        - ./redis_data:/data
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: dev
    container_name: 4atik
    command: >
      sh -c "
        alembic upgrade head &&
        python -m src.main
      "
    restart: always
    ports:
      - '6969:6969'
    env_file:
      - ./server/.env
    volumes:
      - ./server/src:/usr/src/app/src
      - ./server/config:/usr/src/app/config
    networks:
      - chatik-network

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
      target: dev
    container_name: nginx
    restart: always
    ports:
      - '80:8080'
    networks:
      - chatik-network

volumes:
  pg_data:
  mongodb_data:
  redis_data:

networks:
  chatik-network:
