version: '3.9'

services:
  database:
    image: postgres:16
    container_name: database
    restart: always
    ports:
      - '6968:5432'
    env_file:
      - ./server/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - chatik-network

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "17027:27017"
    env_file:
      - ./server/.env
    volumes:
      - mongodb_data:/data/db
    networks:
      - chatik-network

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: 4atik
    restart: always
    ports:
      - '6969:6969'
    env_file:
      - ./server/.env
    volumes:
      - ./server/src:/usr/src/app/src
      - ./server/config:/usr/src/app/config
    networks:
      - chatik-network
  # client:
  #   container_name: client
  #   build:
  #     context: ./client
  #     target: dev
  #     dockerfile: ./Dockerfile
  #   volumes:
  #     - ./client/:/usr/src/app/
  #     - ./client/node_modules/:/usr/src/app/node_modules
  #     - ./client/.next/:/usr/src/app/.next
  #   ports:
  #     - "3232:3000"
  #   networks:
  #     - chatik-network
  # nginx:
  #   build:
  #     context: nginx
  #     dockerfile: Dockerfile
  #   restart: always
  #   container_name: nginx
  #   ports:
  #     - '80:8080'
  #   depends_on:
  #     - server
  #   networks:
  #     - chatik-network

volumes:
  pg_data:
  mongodb_data:


networks:
  chatik-network:
