"""create server models

Revision ID: ef8c3bf0527e
Revises: 5ac803bba65e
Create Date: 2023-12-17 00:40:53.031877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "ef8c3bf0527e"
down_revision: Union[str, None] = "5ac803bba65e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "server",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=70), nullable=False),
        sa.Column("image", sa.String(length=500), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("password", sa.String(length=250), nullable=True),
        sa.Column(
            "admin_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(["admin_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_server_admin_id"), "server", ["admin_id"], unique=False)
    op.create_index(op.f("ix_server_is_public"), "server", ["is_public"], unique=False)
    op.create_table(
        "userserver",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(["server_id"], ["server.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_userserver_user_id"), "userserver", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_userserver_user_id"), table_name="userserver")
    op.drop_table("userserver")
    op.drop_index(op.f("ix_server_is_public"), table_name="server")
    op.drop_index(op.f("ix_server_admin_id"), table_name="server")
    op.drop_table("server")
    # ### end Alembic commands ###
