"""unique bu user id and server id

Revision ID: 41998371cb7e
Revises: e2e11380bdba
Create Date: 2023-12-29 09:41:21.932100

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41998371cb7e"
down_revision: Union[str, None] = "e2e11380bdba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "server", "image", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    op.create_unique_constraint(
        "_user_server_uc", "userserver", ["user_id", "server_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_user_server_uc", "userserver", type_="unique")
    op.alter_column(
        "server", "image", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    # ### end Alembic commands ###
