"""fix user server pk

Revision ID: a7375da748b7
Revises: e2e11380bdba
Create Date: 2023-12-26 15:30:04.590569

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7375da748b7"
down_revision: Union[str, None] = "e2e11380bdba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "server", "image", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "server", "image", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    # ### end Alembic commands ###
