"""add server description

Revision ID: 5f20a0dfb4fb
Revises: 41998371cb7e
Create Date: 2024-01-20 18:01:42.722838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f20a0dfb4fb"
down_revision: Union[str, None] = "41998371cb7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "server", sa.Column("description", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("server", "description")
    # ### end Alembic commands ###
